// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplicationController from "./application_controller"
application.register("application", ApplicationController)

import EmailController from "./email_controller"
application.register("email", EmailController)

import EmailItemController from "./email_item_controller"
application.register("email-item", EmailItemController)

import EmailListController from "./email_list_controller"
application.register("email-list", EmailListController)
